# Generated by Django 6.0.2 on 2026-02-17 10:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('muscle_group', models.CharField(choices=[('CHEST', 'Грудь'), ('BACK', 'Спина'), ('LEGS', 'Ноги'), ('SHOULDERS', 'Плечи'), ('ARMS', 'Руки'), ('CORE', 'Пресс')], max_length=20, verbose_name='Группа мышц')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_custom', models.BooleanField(default=False, verbose_name='Пользовательское')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Упражнение',
                'verbose_name_plural': 'Упражнения',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True, verbose_name='Начало')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='Конец')),
                ('status', models.CharField(choices=[('STARTED', 'Начата'), ('FINISHED', 'Завершена')], default='STARTED', max_length=20, verbose_name='Статус')),
                ('note', models.TextField(blank=True, verbose_name='Заметка')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workouts', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Тренировка',
                'verbose_name_plural': 'Тренировки',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='WorkoutSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(verbose_name='Вес (кг)')),
                ('reps', models.PositiveIntegerField(verbose_name='Повторения')),
                ('rir', models.PositiveIntegerField(blank=True, null=True, verbose_name='RIR')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sets', to='workouts.exercise', verbose_name='Упражнение')),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sets', to='workouts.workout', verbose_name='Тренировка')),
            ],
            options={
                'verbose_name': 'Подход',
                'verbose_name_plural': 'Подходы',
                'ordering': ['created_at'],
            },
        ),
    ]
