# Generated by Django 6.0.2 on 2026-02-17 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='muscle_group',
            field=models.CharField(choices=[('CHEST', 'Грудь'), ('BACK', 'Спина'), ('SHOULDERS', 'Плечи'), ('BICEPS', 'Бицепс'), ('TRICEPS', 'Трицепс'), ('FOREARMS', 'Предплечья'), ('QUADS', 'Квадрицепс'), ('HAMSTRINGS', 'Бицепс бедра'), ('GLUTES', 'Ягодицы'), ('CALVES', 'Икры'), ('CORE', 'Пресс'), ('TRAPS', 'Трапеция'), ('CARDIO', 'Кардио')], max_length=20, verbose_name='Группа мышц'),
        ),
    ]
