# Generated by Django 6.0.2 on 2026-02-17 17:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0003_load_exercises'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledWorkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('time', models.TimeField(blank=True, null=True, verbose_name='Время')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('note', models.TextField(blank=True, verbose_name='Заметка')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Выполнена')),
                ('notify_before', models.PositiveIntegerField(default=30, verbose_name='Напомнить за (минут)')),
                ('exercises', models.ManyToManyField(blank=True, related_name='scheduled_workouts', to='workouts.exercise', verbose_name='Упражнения')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_workouts', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('workout', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule', to='workouts.workout', verbose_name='Фактическая тренировка')),
            ],
            options={
                'verbose_name': 'Запланированная тренировка',
                'verbose_name_plural': 'Запланированные тренировки',
                'ordering': ['date', 'time'],
            },
        ),
    ]
